### ISSUE TITLE
Terms meta table

### ISSUE THREAD

**Issue by shazahm1** [Connections-Business-Directory/Connections#441]
ref:
http://connections-pro.com/support/topic/chosen-js-options

**Comment by shazahm1** [comment]
Todo:

 - [ ] Add new table when installing fresh instance.
 - [ ] Install new table on update.
 - [ ] Refactor the cnMeta class so it can read/write both entry and term meta just like WP core.

**Comment by shazahm1** [comment]
Completed via eff2fb1
